### ISSUE TITLE
Vdr vdr-2.3.1

### ISSUE THREAD

**Issue by hertell** [eikesauer/Permashift#2]
Hi,
Permashift does not compile against vdr-2.3.1.. Will there be a patch for this at some point?

**Comment by eikesauer** [comment]
Thanks for telling me, I don't actively follow VDR development at the moment. 
I will provide a patch, but I cannot yet tell when that will happen.

**Comment by eikesauer** [comment]
I've adapted Permashift's code and added a new patch file for VDR 2.3. I've done only a very basic test (start, rewind), though. Would you test if it works for you?

**Comment by eikesauer** [comment]
So I hope it's all fine. :)
