### ISSUE TITLE
vdr-2.4

### ISSUE THREAD

**Issue by REELcoder** [eikesauer/Permashift#3]
Seems that thinks keep changing....

Compiling for 2.4 faills. Now some class members in cRecorder are declared private. Any ideas?

**Comment by eikesauer** [comment]
I uploaded a patch that makes permashift compile against VDR 2.4.1, but it's functionally untested. Would you please give it a try?

https://github.com/eikesauer/Permashift/blob/f3541d7c0e3e201daf06a49304db0a0d7d5f8dd1/vdr-2.4-patch-for-permashift.diff

**Comment by REELcoder** [comment]
Compiles well and seems to do the job as before with vdr 2.2

Thanks for the help!

**Comment by eikesauer** [comment]
> Compiles well and seems to do the job as before with vdr 2.2

Thanks for testing! (You are the first one to report back...) 

...but did you test with 2.4 or really 2.2?
