### ISSUE TITLE
Avoid reorder warning with gcc11+

### ISSUE THREAD

**Issue by ghost** [eikesauer/Permashift#4]
https://www.vdr-portal.de/forum/index.php?thread/134171-permashift-1-0-4-f%C3%BCr-vdr-2-4-betaversion/&postID=1348103#post1348103

Maybe it's a good idea to fix this in a future 2.6.x patch.

You may want to cherry-pick https://github.com/nvertigo/Permashift/commit/1463c1e6a11705b16c291adbb93202d4d7a1dacf

I don't like pull requests, these make history less readable - IMHO. But if you prefer pull requests drop me a note and I'll create one for the above commit.

**Comment by eikesauer** [comment]
Thanks for keeping Permashift alive and sorry for the huge delay. Pushed your update today.
